# Generated by Django 5.2.7 on 2025-12-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_restaurantprofile_district_restaurantprofile_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
